spring.application.name=BokaSmart
spring.datasource.url=jdbc:mysql://localhost:3306/bokasmart
spring.jpa.database=mysql
spring.datasource.username=root
spring.datasource.password=Miljana834909
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=superSecretKeyThatIsLongEnough123456
